blank_issues_enabled: false # Encourage users to use templates
contact_links:
  - name: Ask a Question / Discussion
    url: https://github.com/juanfkurucz/book-reader/discussions/new # Replace if you use a different forum
    about: Please ask and answer questions here.
  - name: Project Documentation
    url: https://github.com/juanfkurucz/book-reader/blob/main/README.md
    about: Check the README for usage instructions.
