name: Integration Tests

on:
  # Run on workflow_dispatch, release, and before docker publish
  workflow_dispatch:  # Allow manual runs
  release:
    types: [published, prereleased]
  workflow_call:
    # Allow this workflow to be called from other workflows (e.g., docker-publish)
    inputs:
      skip_on_missing_key:
        description: 'Skip tests instead of failing if OPENAI_API_KEY is not set'
        required: false
        default: false
        type: boolean
    secrets:
      OPENAI_API_KEY:
        required: false

jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    # Run this job only if the event is a workflow_dispatch, workflow_call, or a tag starting with 'v'
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -e .
          uv pip install reportlab

      - name: Create sample files
        run: |
          python -m tests.integration.create_samples

      - name: Run integration tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m tests.integration.run_integration_tests ${{ inputs.skip_on_missing_key && '--skip-no-key' || '' }}
