name: Integration Tests

on:
  # Run only on release tags and manual workflow dispatch
  workflow_dispatch:  # Allow manual runs
  release:
    types: [published, prereleased]

jobs:
  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    # Run this job only if the event is a workflow_dispatch or a tag starting with 'v'
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -e .

      - name: Create sample files
        run: |
          python -m integration_tests.create_samples

      - name: Run integration tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m integration_tests.run_integration_tests
