name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies (including dev for ruff/mypy)
      run: uv pip install -e ".[dev]"

    - name: Run Ruff Linting
      run: ruff check .

    - name: Run Ruff Formatting Check
      run: ruff format --check .

    - name: Run MyPy Type Checking
      run: mypy --config-file=pyproject.toml src/
